port 1194
proto udp
dev tun1

ca /etc/openvpn/server-easy-rsa/pki/ca.crt
cert /etc/openvpn/server-easy-rsa/pki/issued/server.crt
key /etc/openvpn/server-easy-rsa/pki/private/server.key
dh /etc/openvpn/server-easy-rsa/pki/dh.pem
tls-auth /etc/openvpn/server/ta.key 0

topology subnet
server 10.9.0.0 255.255.255.0

# Папка с индивидуальными настройками клиентов
client-config-dir /etc/openvpn/ccd
route 192.168.0.0 255.255.255.0
# Сообщаем серверу S1, что LAN-сеть находится за туннелем

# Пушим клиентам интернет через туннель и DNS
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 10.8.0.1"
push "route 192.168.0.0 255.255.255.0"

keepalive 10 60
persist-key
persist-tun
status /var/log/openvpn-status-tun1.log
verb 3
# client-to-client
client-to-client
crl-verify /etc/openvpn/server-easy-rsa/pki/crl.pem
